In [1]:
import numpy as np

In [2]:
np.__file__

'/Users/sakuradariki/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'

In [3]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [7]:
array1.shape

(3, 3)

In [9]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [10]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
array[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [12]:
def change_hundred(array):

    array[0] = 100
    return array

def change_hundred_copy(array):
    
    array_copy = array.copy()
    array_copy[0] = 100
    return array_copy

array_1 = np.arange(0, 4)
array_2 = np.arange(0, 4)

output_array = change_hundred(array_1)
output_array_copy = change_hundred_copy(array_2)

print(array_1)
print(array_2)

[100   1   2   3]
[0 1 2 3]


In [13]:
array_o = np.random.randn(5,5)
array_o

array([[ 1.47635793, -0.2143973 , -0.3222656 , -2.68016441,  0.40572892],
       [-0.72768587, -0.14087916,  0.13743181, -0.4629916 ,  0.5377426 ],
       [ 0.6564603 , -0.41051853,  0.2964021 , -0.52149663, -1.27210489],
       [ 0.24930599,  0.68894289, -0.26689994,  0.76356862,  0.72946643],
       [ 0.43971029,  0.11712558,  0.75046027, -0.56256312, -0.09766969]])

In [21]:
array_o.max()

1.4763579345147155

In [15]:
array_o.argmax()

0

In [16]:
array_o.min()

-2.680164405397871

In [17]:
array_o.argmin()

3

In [18]:
array_o.mean()

-0.01723732002927644

In [19]:
np.median(array_o)

0.11712558182018772

In [20]:
array_o.std()

0.8034600791376463